"""Public package-2E lease-probe source-confirmation API."""

from matrix_auto_cutter.phase2.source_confirmation.assignment import create_stream_assignment
from matrix_auto_cutter.phase2.source_confirmation.capability import ConfirmedSource
from matrix_auto_cutter.phase2.source_confirmation.contracts import (
    ConfirmationDiagnostic,
    ConfirmationErrorCategory,
    ConfirmationErrorCode,
    ConfirmationFailure,
    ConfirmationPorts,
    EvidenceReferences,
    SourceAssignmentRequired,
    SourceConfirmationCancelled,
    SourceConfirmationFailed,
    SourceConfirmationRequest,
    SourceConfirmationResult,
    SourceConfirmed,
    SourceDisappeared,
    SourceInvalidated,
    SourceUnsupported,
    StreamAssignmentCancelled,
    StreamAssignmentConflict,
    StreamAssignmentCreated,
    StreamAssignmentFailed,
    StreamAssignmentRequest,
    StreamAssignmentResult,
)
from matrix_auto_cutter.phase2.source_confirmation.evidence import (
    MAX_MEDIA_PROBE_BYTES,
    MAX_SOURCE_IDENTITY_EVIDENCE_BYTES,
    MAX_STREAM_ASSIGNMENT_BYTES,
    ArtifactReference,
    MediaProbe,
    SourceIdentityEvidence,
    StreamAssignment,
    parse_media_probe_bytes,
    parse_source_identity_evidence_bytes,
    parse_stream_assignment_bytes,
)
from matrix_auto_cutter.phase2.source_confirmation.orchestrator import confirm_source
from matrix_auto_cutter.phase2.source_confirmation.state import (
    SourceState,
    SourceStateInvariantError,
    SourceStateMachine,
)

__all__ = [
    "MAX_MEDIA_PROBE_BYTES",
    "MAX_SOURCE_IDENTITY_EVIDENCE_BYTES",
    "MAX_STREAM_ASSIGNMENT_BYTES",
    "ArtifactReference",
    "ConfirmationDiagnostic",
    "ConfirmationErrorCategory",
    "ConfirmationErrorCode",
    "ConfirmationFailure",
    "ConfirmationPorts",
    "ConfirmedSource",
    "EvidenceReferences",
    "MediaProbe",
    "SourceAssignmentRequired",
    "SourceConfirmationCancelled",
    "SourceConfirmationFailed",
    "SourceConfirmationRequest",
    "SourceConfirmationResult",
    "SourceConfirmed",
    "SourceDisappeared",
    "SourceIdentityEvidence",
    "SourceInvalidated",
    "SourceState",
    "SourceStateInvariantError",
    "SourceStateMachine",
    "SourceUnsupported",
    "StreamAssignment",
    "StreamAssignmentCancelled",
    "StreamAssignmentConflict",
    "StreamAssignmentCreated",
    "StreamAssignmentFailed",
    "StreamAssignmentRequest",
    "StreamAssignmentResult",
    "confirm_source",
    "create_stream_assignment",
    "parse_media_probe_bytes",
    "parse_source_identity_evidence_bytes",
    "parse_stream_assignment_bytes",
]
